//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int ArticleID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Date { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
